spring.application.name=infohub-backend

weather.api.key=${WEATHER_API_KEY:8a4a201f579e1568b4c4e73dc8611627}
weather.api.url=https://api.openweathermap.org/data/2.5/weather
exchange.api.url=https://open.er-api.com/v6/latest/INR
server.port=${PORT:8080}
